/*
 * File: app/view/Step3Panel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NavigationViewDemo.view.Step3Panel', {
  extend: 'Ext.form.Panel',
  alias: 'widget.step3',

  config: {
    padding: 20,
    items: [
      {
        xtype: 'fieldset',
        margin: '0 0 20 0 ',
        title: 'Choose an Operation',
        items: [
          {
            xtype: 'radiofield',
            label: 'Add',
            labelWidth: '50%',
            name: 'operation',
            value: 'add',
            checked: true
          },
          {
            xtype: 'radiofield',
            label: 'Subtract',
            labelWidth: '50%',
            name: 'operation',
            value: 'subtract'
          },
          {
            xtype: 'radiofield',
            label: 'Multiply',
            labelWidth: '50%',
            name: 'operation',
            value: 'multiply'
          },
          {
            xtype: 'radiofield',
            label: 'Divide',
            labelWidth: '50%',
            name: 'operation',
            value: 'divide'
          }
        ]
      },
      {
        xtype: 'button',
        height: 50,
        itemId: 'mybutton2',
        padding: '',
        text: 'Calculate!'
      }
    ]
  }

});